In [ ]:
import pandas as pd

# URLs for Patient and Sample level data
patient_url = "https://media.githubusercontent.com/media/cBioPortal/datahub/master/public/msk_impact_2017/data_clinical_patient.txt"
sample_url = "https://media.githubusercontent.com/media/cBioPortal/datahub/master/public/msk_impact_2017/data_clinical_sample.txt"

# Load both datasets
df_patient = pd.read_csv(patient_url, sep="\t", comment="#")
df_sample = pd.read_csv(sample_url, sep="\t", comment="#")

# Merge on PATIENT_ID
df_msk = pd.merge(df_patient, df_sample, on="PATIENT_ID")

print(f"Combined dataset shape: {df_msk.shape}")
df_msk.head()

Combined Dataset shape: (10945, 23)

,PATIENT_ID,SEX,VITAL_STATUS,SMOKING_HISTORY,OS_MONTHS,OS_STATUS,SAMPLE_ID,SAMPLE_COLLECTION_SOURCE,SPECIMEN_PRESERVATION_TYPE,SPECIMEN_TYPE,...,MATCHED_STATUS,SAMPLE_TYPE,PRIMARY_SITE,METASTATIC_SITE,SAMPLE_CLASS,ONCOTREE_CODE,CANCER_TYPE,CANCER_TYPE_DETAILED,SOMATIC_STATUS,TMB_NONSYNONYMOUS
0,P-0000004,Female,ALIVE,Unknown,NaN,0:LIVING,P-0000004-T01-IM3,Outside,FFPE,Biopsy,...,Matched,Primary,Breast,Not Applicable,Tumor,IDC,Breast Cancer,Breast Invasive Ductal Carcinoma,Matched,17.746485
1,P-0000015,Female,DECEASED,Never,NaN,1:DECEASED,P-0000015-T01-IM3,In-House,FFPE,Biopsy,...,Matched,Metastasis,Breast,Liver,Tumor,IDC,Breast Cancer,Breast Invasive Ductal Carcinoma,Matched,7.764087
2,P-0000023,Male,DECEASED,Never,8.71,1:DECEASED,P-0000023-T01-IM3,In-House,FFPE,Biopsy,...,Matched,Primary,Peritoneum,Not Applicable,Tumor,PEMESO,Mesothelioma,Peritoneal Mesothelioma,Matched,5.545777
3,P-0000024,Female,ALIVE,Prev/Curr Smoker,36.75,0:LIVING,P-0000024-T01-IM3,In-House,FFPE,Resection,...,Matched,Metastasis,Uterus,Lung,Tumor,UEC,Endometrial Cancer,Uterine Endometrioid Carcinoma,Matched,6.654932
4,P-0000025,Female,ALIVE,Never,8.81,0:LIVING,P-0000025-T02-IM5,In-House,FFPE,Biopsy,...,Matched,Metastasis,Uterus,Peritoneum,Tumor,USC,Endometrial Cancer,Uterine Serous Carcinoma/Uterine Papillary Ser...,Matched,1.957439

In [51]:
import io
import tarfile
import requests
import pandas as pd

# Direct download link for the MSK-IMPACT 2017 study archive from cBioPortal
archive_url = "https://datahub.assets.cbioportal.org/msk_impact_2017.tar.gz"

response = requests.get(archive_url)

with tarfile.open(fileobj=io.BytesIO(response.content), mode="r:gz") as tar:
    for member in tar.getmembers():
        if member.name.endswith("data_mutations.txt"):
            f = tar.extractfile(member)
            mut_df = pd.read_csv(f, sep="\t", comment="#", low_memory=False)
            
print(f"Loaded mutation dataset shape: {mut_df.shape}")

pd.set_option('display.max_columns', None)
display(mut_df.head(3))

print(mut_df.columns.tolist())

Loaded mutation dataset shape: (78220, 46)

,Hugo_Symbol,Entrez_Gene_Id,Center,NCBI_Build,Chromosome,Start_Position,End_Position,Strand,Consequence,Variant_Classification,Variant_Type,Reference_Allele,Tumor_Seq_Allele1,Tumor_Seq_Allele2,dbSNP_RS,dbSNP_Val_Status,Tumor_Sample_Barcode,Matched_Norm_Sample_Barcode,Match_Norm_Seq_Allele1,Match_Norm_Seq_Allele2,Tumor_Validation_Allele1,Tumor_Validation_Allele2,Match_Norm_Validation_Allele1,Match_Norm_Validation_Allele2,Verification_Status,Validation_Status,Mutation_Status,Sequencing_Phase,Sequence_Source,Validation_Method,Score,BAM_File,Sequencer,t_ref_count,t_alt_count,n_ref_count,n_alt_count,HGVSc,HGVSp,HGVSp_Short,Transcript_ID,RefSeq,Protein_position,Codons,Hotspot,cDNA_change
0,SPEN,NaN,NaN,GRCh37,1,16265908,16265908,+,missense_variant,Missense_Mutation,SNP,A,A,T,NaN,NaN,P-0000004-T01-IM3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,400,73,NaN,NaN,ENST00000375759.3:c.10981A>T,p.Ile3661Phe,p.I3661F,ENST00000375759,NM_015001.2,3661.0,Att/Ttt,0,c.10981A>T
1,ALK,NaN,NaN,GRCh37,2,29543736,29543736,+,missense_variant,Missense_Mutation,SNP,A,A,G,NaN,NaN,P-0000004-T01-IM3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,180,13,NaN,NaN,ENST00000389048.3:c.1427T>C,p.Val476Ala,p.V476A,ENST00000389048,NM_004304.4,476.0,gTg/gCg,0,c.1427T>C
2,PDCD1,NaN,NaN,GRCh37,2,242793433,242793433,+,missense_variant,Missense_Mutation,SNP,G,G,A,NaN,NaN,P-0000004-T01-IM3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,225,15,NaN,NaN,ENST00000334409.5:c.644C>T,p.Ala215Val,p.A215V,ENST00000334409,NM_005018.2,215.0,gCc/gTc,0,c.644C>T

['Hugo_Symbol', 'Entrez_Gene_Id', 'Center', 'NCBI_Build', 'Chromosome', 'Start_Position', 'End_Position', 'Strand', 'Consequence', 'Variant_Classification', 'Variant_Type', 'Reference_Allele', 'Tumor_Seq_Allele1', 'Tumor_Seq_Allele2', 'dbSNP_RS', 'dbSNP_Val_Status', 'Tumor_Sample_Barcode', 'Matched_Norm_Sample_Barcode', 'Match_Norm_Seq_Allele1', 'Match_Norm_Seq_Allele2', 'Tumor_Validation_Allele1', 'Tumor_Validation_Allele2', 'Match_Norm_Validation_Allele1', 'Match_Norm_Validation_Allele2', 'Verification_Status', 'Validation_Status', 'Mutation_Status', 'Sequencing_Phase', 'Sequence_Source', 'Validation_Method', 'Score', 'BAM_File', 'Sequencer', 't_ref_count', 't_alt_count', 'n_ref_count', 'n_alt_count', 'HGVSc', 'HGVSp', 'HGVSp_Short', 'Transcript_ID', 'RefSeq', 'Protein_position', 'Codons', 'Hotspot', 'cDNA_change']

In [68]:
# Ensure each patient is only counted once per gene (in case of multiple mutations per patient per gene)
unique_muts = mut_df[['Tumor_Sample_Barcode', 'Hugo_Symbol']].drop_duplicates()

# Count how many unique patients have a mutation for each gene
top_10_genes = unique_muts['Hugo_Symbol'].value_counts().head(10).index.tolist()

print(top_10_genes)

['TP53', 'KRAS', 'TERT', 'PIK3CA', 'APC', 'ARID1A', 'MLL2', 'PTEN', 'MLL3', 'EGFR']

In [70]:
# Filter the mutation dataframe to only include rows for these top 10 genes
filtered_muts = mut_df[mut_df['Hugo_Symbol'].isin(top_10_genes_list)]
print(f"Filtered mutation dataset shape: {filtered_muts.shape}")

Filtered mutation dataset shape: (16028, 46)

In [75]:
# Transform mutation data into one patient per row, one gene per column format (binary mutation matrix)
# (1 = mutated, 0 = wild-type)
# Rows = samples, Columns = genes
gene_matrix = pd.crosstab(filtered_muts['Tumor_Sample_Barcode'], filtered_muts['Hugo_Symbol'])
gene_matrix = (gene_matrix > 0).astype(int)

# Add mut prefix to the column names so they are easy to identify
gene_matrix.columns = [f"mut_{gene}" for gene in gene_matrix.columns]

# Merge the binary mutation matrix onto your existing clinical dataframe (df_msk)
merge_col = 'SAMPLE_ID'

df_final = df_msk.merge(gene_matrix, left_on=merge_col, right_index=True, how='left')

# Fill missing values for the new mutation columns with 0 (since absence in the mutation table means no mutation detected)
df_final[mut_cols] = df_final[mut_cols].fillna(0).astype(int)

print(f"Final merged dataset shape: {df_final.shape}")
print(df_final.head(5))

Final merged dataset shape: (10945, 33)
  PATIENT_ID     SEX VITAL_STATUS   SMOKING_HISTORY  OS_MONTHS   OS_STATUS  \
0  P-0000004  Female        ALIVE           Unknown        NaN    0:LIVING
1  P-0000015  Female     DECEASED             Never        NaN  1:DECEASED
2  P-0000023    Male     DECEASED             Never       8.71  1:DECEASED
3  P-0000024  Female        ALIVE  Prev/Curr Smoker      36.75    0:LIVING
4  P-0000025  Female        ALIVE             Never       8.81    0:LIVING

           SAMPLE_ID SAMPLE_COLLECTION_SOURCE SPECIMEN_PRESERVATION_TYPE  \
0  P-0000004-T01-IM3                  Outside                       FFPE
1  P-0000015-T01-IM3                 In-House                       FFPE
2  P-0000023-T01-IM3                 In-House                       FFPE
3  P-0000024-T01-IM3                 In-House                       FFPE
4  P-0000025-T02-IM5                 In-House                       FFPE

  SPECIMEN_TYPE  DNA_INPUT  SAMPLE_COVERAGE  TUMOR_PURITY MATCHED_STATUS  \
0        Biopsy      250.0            428.0          50.0        Matched
1        Biopsy      198.0            281.0          40.0        Matched
2        Biopsy      250.0            454.0          30.0        Matched
3     Resection      250.0           1016.0          40.0        Matched
4        Biopsy      250.0           1147.0          30.0        Matched

  SAMPLE_TYPE PRIMARY_SITE METASTATIC_SITE SAMPLE_CLASS ONCOTREE_CODE  \
0     Primary       Breast  Not Applicable        Tumor           IDC
1  Metastasis       Breast           Liver        Tumor           IDC
2     Primary   Peritoneum  Not Applicable        Tumor        PEMESO
3  Metastasis       Uterus            Lung        Tumor           UEC
4  Metastasis       Uterus      Peritoneum        Tumor           USC

          CANCER_TYPE                               CANCER_TYPE_DETAILED  \
0       Breast Cancer                   Breast Invasive Ductal Carcinoma
1       Breast Cancer                   Breast Invasive Ductal Carcinoma
2        Mesothelioma                            Peritoneal Mesothelioma
3  Endometrial Cancer                     Uterine Endometrioid Carcinoma
4  Endometrial Cancer  Uterine Serous Carcinoma/Uterine Papillary Ser...

  SOMATIC_STATUS  TMB_NONSYNONYMOUS  mut_APC  mut_ARID1A  mut_EGFR  mut_KRAS  \
0        Matched          17.746485        0           0         0         0
1        Matched           7.764087        0           0         0         0
2        Matched           5.545777        0           0         0         0
3        Matched           6.654932        0           1         0         0
4        Matched           1.957439        0           0         0         0

   mut_MLL2  mut_MLL3  mut_PIK3CA  mut_PTEN  mut_TERT  mut_TP53
0         1         1           0         0         0         1
1         0         0           1         0         0         1
2         0         0           0         0         0         0
3         0         0           0         1         0         0
4         0         0           1         0         0         1